apiVersion: v1
kind: Service
metadata:
  name: clustered-service-jobs-service
spec:
  selector:
    app: clustered-service-jobs
  type: NodePort
  ports:
    - protocol: TCP
      name: admin
      nodePort: 30082
      port: 8080  # The port exposed by the service
      targetPort: 8080  # The port the pod listens on

