apiVersion: v1
kind: Service
metadata:
  name: job-executor-service
spec:
  selector:
    app: clustered-service-job-executor
  type: ClusterIP
  ports:
    - protocol: TCP
      name: exec
      port: 8082  # The port exposed by the service
      targetPort: 8080  # The port the pod listens on

